version: "3.8"
services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - db_network
    restart: always
  koa-app:
    container_name: koa-app
    build: .
    image: anjeonghoo/koa-application
    environment:
      - SPRING_DATASOURCE_USERNAME=koadatabase
      - SPRING_DATASOURCE_PASSWORD=koadatabase
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "80:8080"
    restart: always
    depends_on:
      - redis
    networks:
      - db_network
networks:
    db_network:
        driver: bridge
