version: "3.8"                                          # 파일 규격 버전
services:                                               # 이 항목 밑에 실행하려는 컨테이너들을 정의
  koa-database:
    container_name: koa-application
    build:
      dockerfile: Dockerfile
      context: ./database
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=koa
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
