spring:

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  h2-console:
    settings:
      web-allow-others: false

  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
        show_sql: true

jwt:
  secret: Thisistheattendanceappserviceforthekusitmsconferenceandthisisaverylongsecertkey
  access-token-expiration-time: 86400000 #  24*60*60*1000 = 1일
  refresh-token-expiration-time: 604800000 # 7*24*60*60*1000 = 7일
  reissue-refresh-token-expiration-time: 259200000 # 24*60*60*1000 = 3일


logging:
  level:
    org:
      hibernate.sql: debug
